### ISSUE TITLE
Could you please provide the related configuration files of OCR+CAR? Thank you very much.

### ISSUE THREAD

**Issue by Adele0108** [edwardyehuang/CAR#5]

**Comment by edwardyehuang** [comment]
Hi @Adele0108 

You may refer to the [ResNet-50 + Self-Attention](../blob/master/configs/pascalcontext_train_resnet50_sa_car.cfg) configs we provided, and then add/change the lines below:

```
--hrnet_w48_weights_path=<To the path of HRNetW48 h5 weights>
--aux_loss=True
--head=ocr
```

**Comment by Adele0108** [comment]
Okay, I'll try this. Thank you.
